{{- if .Values.prometheus.monitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "tracker.fullname" . }}
  labels:
    {{- include "tracker.labels" . | nindent 4 }}
    {{- if .Values.prometheus.monitor.additionalLabels }}
    {{ toYaml .Values.prometheus.monitor.additionalLabels | indent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ template "tracker.name" . }}
      release: {{ .Release.Name }}
  endpoints:
    - port: metrics
      {{- if .Values.prometheus.monitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.prometheus.monitor.scrapeTimeout }}
      {{- end }}
      {{- if .Values.prometheus.monitor.relabelings }}
      relabelings:
      {{ toYaml .Values.prometheus.monitor.relabelings | nindent 8 }}
      {{- end }}
{{- end -}}

{{- if .Values.victoriametrics.monitor.enabled -}}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: {{ include "tracker.fullname" . }}
  labels:
    {{- include "tracker.labels" . | nindent 4 }}
    {{- if .Values.victoriametrics.monitor.additionalLabels }}
    {{ toYaml .Values.victoriametrics.monitor.additionalLabels | indent 4 }}
    {{- end }}
spec:
  endpoints:
    - path: /metrics
      port: metrics
      scrapeTimeout: {{ .Values.victoriametrics.monitor.scrapeTimeout }}
      {{- if .Values.victoriametrics.monitor.relabelings }}
      relabelConfigs: 
      {{ toYaml .Values.victoriametrics.monitor.relabelings | nindent 8 }}
      {{- end }}
  jobLabel: {{ template "tracker.fullname" . }}
  selector:
    matchLabels:
      {{- include "tracker.selectorLabels" . | nindent 8 }}
{{- end -}}
